language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 'node'
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
install:
  - npm install
#  - npm prune // Broken because of https://github.com/npm/npm/issues/17781
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
  - npm run lint
  - make dist
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
